### ISSUE TITLE
Please tell me your operating environment.

### ISSUE THREAD

**Issue by pdc-kaminaga** [sdanaipat/fairseq-translator#5]
Please tell me your operating environment.
I used Google Colab + Google Drive.
My first goal is to get the same result as sample.jpg.
I ran one "Train-[GPU].jpynb/first fresh" and 20 "Train-[GPU].jpynb/loded checkpoints"(12h limit). 
But I still can't get the same result as sample.jpg.

translate(["It took me two nights to learn Japanese."])
1st test
[-6.9480] 私に聞きなさい。
[-7.1193] 私に聞いて。
[-7.1386] 私を学びました。
[-7.2463] わかりました。
[-7.3973] 私にあった。
[-7.7728] 私に聞いてください。
[-7.8879] 私は日本語を学びました。
[-7.9125] 私に聞いてくれ。
[-7.9764] 私のことを学びました。
[-8.0168] 私の言うことを聞いた。
・
・
19th test
[-3.7086] 私は日本人です。
[-4.5044] 私は日本語を学んだ。
[-4.9637] 日本人です。
[-5.2527] 私は日本人になりました。
[-5.3237] 私は日本人だ。
[-5.4526] 私は日本語を学ぶ。
[-5.6783] 日本語を学んだ。
[-6.1220] 僕は日本人です。
[-6.2268] 私は日本語を学んでいる。
[-6.3604] 私は日本語を学びました。
[-6.4290] 私は日本人になった。

20th test
[-5.5796] 私のおごりだ。
[-5.8163] 私は日本人です。
[-5.8172] 日本人です。
[-6.3387] 私のおかげです。
[-6.9103] 私は、日本人です。
[-6.9773] 私のおごりですよ。
[-7.2679] 僕のおごりだ。
[-7.4016] 私は日本人だ。
[-7.4967] 私が日本人です。
[-7.5173] 私はそれを学びました。

**Comment by sdanaipat** [comment]
Hi, I trained it on a titan X (pascal) for 5-7 days (can't remember the exact number, but it was longer than 12 hours).

**Comment by pdc-kaminaga** [comment]
Thanks for your reply.
I won't give up, I'll keep working hard towards my goal.
